### PR TITLE
invert order of implode() for PHP8 compat

### PR DESCRIPTION
**Pull request by moraleida**
### 🎫 Ticket

https://www.php.net/manual/en/function.implode.php

[TICKET_ID] 

### ✔️ Checklist
- [ ] I've included a changelog entry in the readme.txt file. 
- [ ] My code is tested. 
- [ ] My code has [proper inline documentation](https://the-events-calendar.github.io/products-engineering/docs/code-standards/).

### CODE REVIEW

**Comment by bordoni** [comment]
How does this play on a version before PHP 8?

**Comment by moraleida** [comment]
> How does this play on a version before PHP 8?

Separator after the array was the old signature. Up to 7.4 either order of params works, but this was deprecated in 7.4 and removed in 8.0, forcing the order to be `separator, array`: https://www.php.net/manual/en/migration74.deprecated.php

**Review by Camwyn — APPROVED** [review]

**Comment by Camwyn** [comment]
Note this is based on master - it needs to go into a release or hotfix branch before merging! (thus the hold label)

**Comment by rafsuntaskin** [comment]
This is already commited in B22.scone branch: https://github.com/the-events-calendar/event-tickets/pull/2479/commits/8710556e97426aff4963b59a445cf9e5225b1fdf

**Pull request closed without merging**
