### PR TITLE
[ET-1504] Fix Typo in Value Utility for Tickets Commerce

### PR DESCRIPTION
**Pull request by codingmusician**
### 🎫 Ticket

[ET-1504] 

### 🗒️ Description

Quick and simple typo fix. Missing `=`.

### 🎥 Artifacts 

N/A

### ✔️ Checklist
- [x] I've included a changelog entry in the readme.txt file. 
- [x] My code is tested. 
- [x] My code has [proper inline documentation](https://the-events-calendar.github.io/products-engineering/docs/code-standards/).

[ET-1504]: https://theeventscalendar.atlassian.net/browse/ET-1504?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by bordoni — APPROVED** [review]

**Review by juanfra — APPROVED** [review]
Looking good! please note that [there was a PR opened for this](https://github.com/the-events-calendar/event-tickets/pull/2393) - would you please take the yoda conditional fix and the readme sync from that one?

**Comment by codingmusician** [comment]
@juanfra I added the yoda conditional into this PR. Are you needing me to just tweak the wording for the readme? I saw you had some weird merge issue in your PR. Sorry I didn't see that you had a PR for this already.

**Comment by juanfra** [comment]
@codingmusician thanks for the yoda conditional! As for the readme entries, I'm fixing the merge from the last release (master merged to lambeosaurus) where all of the readme entries for this release were moved to 5.3.3 - You can check my commit fixing that [here](https://github.com/the-events-calendar/event-tickets/pull/2393/commits/d7032ab4314eb7f93922fa1c4edab75cf3cf94cc)

**Comment by codingmusician** [comment]
> @codingmusician thanks for the yoda conditional! As for the readme entries, I'm fixing the merge from the last release (master merged to lambeosaurus) where all of the readme entries for this release were moved to 5.3.3 - You can check my commit fixing that [here](https://github.com/the-events-calendar/event-tickets/pull/2393/commits/d7032ab4314eb7f93922fa1c4edab75cf3cf94cc)

Got it. I was kind of curious why the readme seemed a bit light. LOL!

**Review by juanfra — APPROVED** [review]

**Review by juanfra — APPROVED** [review]

**Review by bordoni — APPROVED** [review]

**Pull request merged**
