### PR TITLE
Implement Ticket Cache

### PR DESCRIPTION
**Pull request by lucatume**
### 🎫 Ticket

[ET-1808](https://theeventscalendar.atlassian.net/browse/ET-1808) 

### 🗒️ Description

Phase 1 of the Event Tickets performance project.
Based on [Common PR](https://github.com/the-events-calendar/tribe-common/pull/1951).
This adds in-request and object caching for Ticket objects for all providers.
The code updates to the ticket fetching logic is not that complex, and most work went into making sure that what could affect a ticket values is monitored to invalidate the ticket cache when required.
Currently, a Ticket cache is invalidated when:
* the Ticket is updated or deleted via ET API
* the Ticket post is updated deleted via WP API (`wp_insert_post` and `wp_delete_post`)
* a Ticket meta is updated; this is a conservative approach that will invalidate on any meta update to avoid having to track and maintain all the possible meta keys that would require, or not, cache invalidation.
* when a post that might affect the Ticket object is created, updated or deleted. i.e. Attendees and Orders.

There is no UI change or behavior change.
The work is fully covered by existing and dedicated tests.

Bonus points: 
* I've removed `lucatume/function-mocker` to replace its uses with `uopz`. This speeds up tests quite a bit.
* I've fixed a REST API issue that would append a trailing space (` `) to each availability information in Ticket responses.

### ✔️ Checklist
- [x] I've included a changelog entry in the readme.txt file. 
- [x] My code is tested. 
- [x] My code has [proper inline documentation](https://the-events-calendar.github.io/products-engineering/docs/code-standards/).

[ET-1808]: https://theeventscalendar.atlassian.net/browse/ET-1808?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by codingmusician — APPROVED** [review]

**Comment by rafsuntaskin** [comment]
@juanfra @lucatume We should have a Jira ticket for this as QA still needs to keep these changes in mind while doing holistic tests.

**Comment by lucatume** [comment]
> @juanfra @lucatume We should have a Jira ticket for this as QA still needs to keep these changes in mind while doing holistic tests.

I've added the ticket ([ET-1808](https://theeventscalendar.atlassian.net/browse/ET-1808)).
Regarding the holistic tests: you're correct. Ideally this could be QAed in branch.

**Comment by lucatume** [comment]
Please note this [commit](https://github.com/the-events-calendar/event-tickets/pull/2708/commits/341d10bfe30b1079c8e8e0bf3f1967a3e28aead7): I've fixed a bug that would be order-dependant and that would pop-up in testing every now and then.

**Review by codingmusician — APPROVED** [review]

**Review by redscar — APPROVED** [review]
I learned a few things reading through your tests. Thanks :+1:

**Pull request merged**
